### ISSUE TITLE
Is pooling correct?

### ISSUE THREAD

**Issue by Skeeve** [RUB-NDS/WS-TLS-Scanner#12]
Hi!

When I take a look at catalina.out I can see messages like this:

    08:29:11.453 [pool-20060-thread-1] INFO  probe.TlsProbe - Executing:PROTOCOL_VERSION
    08:29:15.162 [pool-20060-thread-1] INFO  probe.TlsProbe - Finished PROTOCOL_VERSION -  Took 3s
    08:29:15.162 [pool-20060-thread-1] INFO  probe.TlsProbe - Executing:CIPHERSUITE
    08:29:19.134 [catalina-exec-2] INFO  tls.ws.ScannerWS - Received a request to scan: http://…
    08:29:19.134 [pool-4-thread-1] INFO  tls.TlsScannerCallback - Scanning: http://…
    08:29:19.225 [pool-20061-thread-1] INFO  probe.TlsProbe - Executing:SNI
    08:29:19.382 [pool-20061-thread-1] INFO  probe.TlsProbe - Finished SNI -  Took 0s
    08:29:19.382 [pool-20061-thread-1] INFO  probe.TlsProbe - Executing:COMPRESSIONS

Is it correct to assume that "thread-X" is for the thread which runs?

As far as I know you allow 10 threads at the moment. So how does it come that I only observe thread 1 and 2?

    $ perl -ne 'next unless /\[pool-\d+-(thread-\d+)/; ++$thread{$1}; END { use Data::Dumper; print Dumper \%thread }' catalina.*
    $VAR1 = {
          'thread-2' => 3274,
          'thread-1' => 66077
        };

**Comment by Skeeve** [comment]
Update: In staging it seems to work:

     $ perl -ne 'next unless /\[pool-\d+-(thread-\d+)/; ++$thread{$1}; END { use Data::Dumper; print Dumper \%thread }' catalina.*
    $VAR1 = {
          'thread-7' => 1027,
          'thread-9' => 252,
          'thread-6' => 250,
          'thread-10' => 249,
          'thread-5' => 1053,
          'thread-8' => 226,
          'thread-1' => 208077,
          'thread-2' => 11307,
          'thread-4' => 1109,
          'thread-3' => 288
        };

**Comment by ic0ns** [comment]
There is pooling in Production, it just works differently. WS-TLS supports two types of Pooling. One for each individual Scanjob and one for all scan jobs as a whole. Thats also bascially what you see here:
`08:29:11.453 [pool-20060-thread-1] INFO  probe.TlsProbe - Executing:PROTOCOL_VERSION`
pool 20060 thread 1 means we already have 20060 Threadpools created. Since each Scanjob is executed single threaded the thread number is one.

**Comment by Skeeve** [comment]
So how do I make it work the same?

**Comment by ic0ns** [comment]
Maybe there is a missunderstanding. The threadpool has (in the old version) some automatic size adjustments. When he is not heavily used he will shrink its thread count to (i think) 2 Threads to safe system resources. He will automatically increase again once he gets under heavier load (to a maximum of 10 Threads). In the new version i removed this auto shrinking since it seemed to confuse more than its  useful since the threadpool is unser heavy load most of the time anyways. Basically nothing changed. Just the auto adjustment got removed and the threadpool is now always a fixed size.
